name: create-release
on:
  workflow_dispatch:

jobs:
  test-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Testing and linting
        uses: ./.github/workflows/pull_request.yml
  docker:
    runs-on: ubuntu-latest
    needs: test-and-linting
    if: ${{ success() }}
    env:
      REGISTRY_ID: crpkbormehnpcu7gaie8
    steps:
      - name: create new release branch
        run: git checkout -b releases/${{ github.run_number }}
      - name: create docker image
        run: | 
          docker build . -t cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }} 
          cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}_latest
      - name: push docker image
        run: docker push cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}
          cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}_latest
      - name: creating git tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
      - name: creating issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ github.run_number }}
      - name: Update CHANGELOG.md
        uses: actions/write-to-file@v1.0
        with:
          filename: ./CHANGELOG.md
          content: ${{ github.run_number }}
