name: create-release
on:
  workflow_dispatch:

jobs:
  login-to-docker:
    name: Test Docker
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  test-and-linting:
      uses: ./.github/workflows/pull_request.yml
  docker:
    runs-on: ubuntu-latest
    needs: test-and-linting
    if: ${{ success() }}
    env:
      REGISTRY_ID: crpkbormehnpcu7gaie8
    steps:
      - uses: actions/checkout@v4
      - name: create new release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: v${{ github.run_number }}
          sha: ${{ github.event.pull_request.head.sha }}
      - name: create docker image
        run: | 
          docker build . -t cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }} -t cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}_latest
      - name: push docker image
        run: docker push -a cr.yandex/${{ env.REGISTRY_ID }}/app
  update-repo:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - name: creating git tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
      - name: creating issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ github.run_number }}
      - name: Update CHANGELOG.md
        uses: frdrwrt/write-to-file@v1.3
        with:
          filename: ./CHANGELOG.md
          content: ${{ github.run_number }}
