name: handling-pull-requests
on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.14.0
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: |
          npm ci
          npm run build
          npm test

  linting:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.14.0
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: |
          npm ci
          npm run build
          npm run lint test

