name: release-to-production
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (only number)'
        required: true
        default: '0'
        type: string
jobs:
